// <auto-generated />
using System;
using ApiWebLichSu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiWebLichSu.Migrations
{
    [DbContext(typeof(MyDbcontext))]
    [Migration("20240216130754_up1")]
    partial class up1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiWebLichSu.Model.Catogery", b =>
                {
                    b.Property<int>("ID_CATOGERY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CATOGERY"), 1L, 1);

                    b.Property<string>("NAME_CATOGERY")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_CATOGERY");

                    b.ToTable("Catogery", (string)null);
                });

            modelBuilder.Entity("ApiWebLichSu.Model.Comment", b =>
                {
                    b.Property<int>("COMNENT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("COMNENT_ID"), 1L, 1);

                    b.Property<string>("CONTENT_COMMENT")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_USER")
                        .HasColumnType("int");

                    b.HasKey("COMNENT_ID");

                    b.HasIndex("ID_USER");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("ApiWebLichSu.Model.History", b =>
                {
                    b.Property<int>("ID_HISTORY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_HISTORY"), 1L, 1);

                    b.Property<string>("CONTENT")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATESUBMIT")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_CATOGERY")
                        .HasColumnType("int");

                    b.Property<int>("ID_USER")
                        .HasColumnType("int");

                    b.Property<string>("TITLE")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_HISTORY");

                    b.HasIndex("ID_CATOGERY");

                    b.HasIndex("ID_USER");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("ApiWebLichSu.Model.Permission", b =>
                {
                    b.Property<int>("PER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PER_ID"), 1L, 1);

                    b.Property<string>("CONTENT_PERMISSION")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ID_USER")
                        .HasColumnType("int");

                    b.HasKey("PER_ID");

                    b.HasIndex("ID_USER");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("ApiWebLichSu.Model.Users", b =>
                {
                    b.Property<int>("ID_USER")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_USER"), 1L, 1);

                    b.Property<string>("NAME_USER")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PASSWORD_USER")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_USER");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ApiWebLichSu.Model.Comment", b =>
                {
                    b.HasOne("ApiWebLichSu.Model.Users", "USER")
                        .WithMany("Comments")
                        .HasForeignKey("ID_USER")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("USER");
                });

            modelBuilder.Entity("ApiWebLichSu.Model.History", b =>
                {
                    b.HasOne("ApiWebLichSu.Model.Catogery", "CATOGERY")
                        .WithMany("HISTORY")
                        .HasForeignKey("ID_CATOGERY")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiWebLichSu.Model.Users", "USERS")
                        .WithMany("Historys")
                        .HasForeignKey("ID_USER")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CATOGERY");

                    b.Navigation("USERS");
                });

            modelBuilder.Entity("ApiWebLichSu.Model.Permission", b =>
                {
                    b.HasOne("ApiWebLichSu.Model.Users", "Users")
                        .WithMany("Permissions")
                        .HasForeignKey("ID_USER")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ApiWebLichSu.Model.Catogery", b =>
                {
                    b.Navigation("HISTORY");
                });

            modelBuilder.Entity("ApiWebLichSu.Model.Users", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Historys");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
